# Site settings
title: RUDAT company blog
description: RUDAT company blog
baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://rudat.github.io" # the base hostname & protocol for your site e.g

# User settings
username: RUDAT
user_description: RUDAT is the gratest android development company in the world
user_title: Software Development Company
email: rudat.info@gmail.com
github_username:  rudat

exclude: ['package.json', 'src' , 'node_modules']
